# Generated by Django 4.1.2 on 2022-10-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='senderMail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
