# Generated by Django 4.1.2 on 2022-10-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commentmodel_sendermail_alter_commentmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='sender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
