# Generated by Django 4.1.2 on 2022-10-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categorymodel_productsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsmodel',
            name='img',
        ),
    ]
