# Generated by Django 4.1.2 on 2022-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
