# Generated by Django 4.1.2 on 2022-10-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='img',
        ),
        migrations.AddField(
            model_name='cart',
            name='productId',
            field=models.IntegerField(null=True),
        ),
    ]
