# Generated by Django 4.1.2 on 2022-10-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_cart_img_cart_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
